Split packets
advanced-navigation/python pull request #10
Opened 2023-07-25 01:04 UTC by JoshLeo-adnav

- Split all packets into separate files
- Fix incorrect/outdated packet definitions
- Initialise all packet fields on creation
- Simplify/improve structure of encode/decode of packets
- Optimise and improve packet decoding process
- Add certus TCP example

2023-07-27 23:49 UTC, mattia-adnav commented on an_devices/advanced_navigation_device_tcp.py
> +##                     Copyright 2021, Advanced Navigation                    ##
Update header to 2023

2023-07-27 23:55 UTC, mattia-adnav commented on anpp_packets/an_packet_1.py
> +            data += pack("<B", PacketID(packet).value)
Use _structure as you have done for other packets for consistency

2023-07-28 00:05 UTC, mattia-adnav commented on anpp_packets/an_packet_195.py
This packet has 2 different definitions. One for the spatial series and one for H7. The file will need to have both definitions. See packet 28 for an example of this

2023-07-28 00:07 UTC, mattia-adnav commented on anpp_packets/an_packet_2.py
> +        data = pack("<B", self.boot_mode.value)
_structure

2023-07-28 00:08 UTC, mattia-adnav commented on anpp_packets/an_packet_202.py
> +from struct import pack
remove and user struct.pack instead if you still need it

2023-07-28 00:14 UTC, mattia-adnav commented on anpp_packets/an_packet_55.py
> +from typing import List, Optional
List is unused?

2023-07-28 00:20 UTC, mattia-adnav commented on anpp_packets/an_packet_86.py
> +##                     Copyright 2022, Advanced Navigation                    ##
2023

2023-07-28 00:22 UTC, mattia-adnav commented on anpp_packets/an_packets.py
> +from enum import Enum, IntEnum
remove Enum

2023-07-28 00:23 UTC, mattia-adnav commented on ci_tests/packet_tests/decode_test.py
> +##                            an_packet_1_test.py                             ##
change name. 2023

2023-07-28 00:23 UTC, mattia-adnav commented on ci_tests/packet_tests/encode_decode_test.py
> +##                            an_packet_1_test.py                             ##
change name. 2023

2023-07-28 00:24 UTC, mattia-adnav commented on ci_tests/packet_tests/encode_test.py
> +##                            an_packet_1_test.py                             ##
change name. 2023

2023-07-28 00:25 UTC, mattia-adnav commented on examples/certus_tcp_example.py
> +##                              certus_example.py                             ##
change name. 2023

2023-07-28 00:26 UTC, mattia-adnav commented on requirements.txt
> +pyserial==3.5
in the readme you have >=

2023-07-28 00:31 UTC, mattia-adnav commented on anpp_packets/an_packet_3.py
> +    _structure = struct.Struct("<BHB")
missing element for the serial number

2023-07-28 00:35 UTC, mattia-adnav commented on anpp_packets/an_packet_195.py
8Hz missing

2023-07-28 00:40 UTC, mattia-adnav commented on anpp_packets/an_packet_protocol.py
> +                    self.decode_iterator += (
As discussed, we need to find a way to keep the buffer size in check

2023-07-28 00:41 UTC, mattia-adnav requested changes
I made a few comments. Please resolve before merging

2023-07-28 00:42 UTC, luke-adnav commented on an_devices/advanced_navigation_device_serial.py
> +from anpp_packets import *
It doesn't look like this is being used (+ generally good to avoid importing all)
```suggestion
```

2023-07-28 00:42 UTC, luke-adnav commented on an_devices/advanced_navigation_device_serial.py
>              print(f"Baud Rate:{baud} is not valid")
Should we be throwing error? Do we want to allow/can we handle no port/baud

2023-07-28 00:42 UTC, luke-adnav commented on an_devices/advanced_navigation_device_serial.py
> +                f"Packet_example currently only supports Windows and Linux operating systems."
Doesn't need to be f-string

2023-07-28 00:42 UTC, luke-adnav commented on an_devices/advanced_navigation_device_tcp.py
> +##                        advanced_navigation_device.py                       ##
```suggestion
##                        advanced_navigation_device_tcp.py                   ##
```

2023-07-28 00:42 UTC, luke-adnav commented on an_devices/advanced_navigation_device_tcp.py
> +# Copyright (C) 2021 Advanced Navigation                                       #
```suggestion
# Copyright (C) 2023 Advanced Navigation                                       #
```

2023-07-28 00:42 UTC, luke-adnav commented on an_devices/advanced_navigation_device_tcp.py
> +from anpp_packets import *
Seems unused
```suggestion
```

2023-07-28 00:42 UTC, luke-adnav commented on an_devices/advanced_navigation_device_tcp.py
> +            print(f"Port:{address} is not valid")
"Address:" or port?

2023-07-28 00:42 UTC, luke-adnav commented on an_devices/advanced_navigation_device_tcp.py
> +        self.port = port
Port validation?

2023-07-28 00:42 UTC, luke-adnav commented on an_devices/advanced_navigation_device_tcp.py
> +        self.logFile = None
Are these used?

2023-07-31 02:22 UTC, mattia-adnav approved these changes

2023-07-31 02:23 UTC, luke-adnav commented on an_devices/advanced_navigation_device_serial.py
>              self.baud = baud
Should baud be stored as an int or expected to be passed as an int? This code could take a string that is convertible to a valid int and store it as a string. ie
```suggestion
        if isinstance(baud, int) and baud in self.valid_baud_rates:
            self.baud = baud
```
or
```suggestion
        if int(baud) in self.valid_baud_rates:
            self.baud = int(baud)
```

2023-07-31 02:26 UTC, merged

2023-07-31 02:27 UTC, luke-adnav commented on an_devices/advanced_navigation_device_tcp.py
> +            return self.tcp.recv(64)
Would we ever want a different size? Would it be useful to have a default arg `buf_size=64` and allow different sizes to be passed?